# This is the deployment part of the CI/CD flow which triggers only on pull requests to master

name: CD

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/


    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        
    - name: Install dependencies
      run: npm ci
    
    - name: Deploy
      run: |
        git config --global user.name dkadillak
        git config --global user.email devin.kadillak@gmail.com
        git remote set-url origin https://dkadillak:${{ github.token }}@github.com/${{ github.repository }}
        npm run deploy
