# This is the deployment part of the CI/CD flow which triggers when a pull request into master is merged

name: CD

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  build:

    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/


    steps:
    - name: Checkout repository
      id: checkout
      if: github.event.pull_request.merged == true
      uses: actions/checkout@v2
      
    - name: Set up Node.js ${{ matrix.node-version }}
      id: node
      uses: actions/setup-node@v1
      if: github.event.pull_request.merged == true
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      if: github.event.pull_request.merged == true
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' && github.event.pull_request.merged == true
      run: npm ci
    
    - name: Deploy
      id: deploy
      if: github.event.pull_request.merged == true
      run: |
        node node_modules/gh-pages/bin/gh-pages-clean
        git config --global user.name dkadillak
        git config --global user.email devin.kadillak@gmail.com
        git remote set-url origin https://dkadillak:${{ github.token }}@github.com/${{ github.repository }}
        npm run deploy
