# This is the workflow specifically for the Continuous Integration portion of the deployment, which will run whenever the upstream branch 'development' has been pushed to

name: CI

on:
  push:
    branches: [ development ]

jobs:
  build:

    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository
      id: checkout
      uses: actions/checkout@v2
      
    - name: Set up Node.js ${{ matrix.node-version }}
      id: node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
    
    - name: Run tests (not in watcher mode)
      id: test
      run: sudo CI=true npm test -- --coverage
    
    - name: Upload coverage to Codecov
      id: codecov
      uses: codecov/codecov-action@v1
    
    - name: Lint
      id: lint
      uses: stefanoeb/eslint-action@1.0.2
      with: 
        files: src/
    
