# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests (not in watcher mode)
      run: sudo CI=true npm test -- --coverage
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
    
    - name: Build
      run: npm run build
    
    - name: Deploy
      run: |
        git config --global user.name dkadillak
        git config --global user.email devin.kadillak@gmail.com
        git remote set-url origin https://dkadillak:${{ github.token }}@github.com/${{ github.repository }}
        npm run deploy
